POST http://localhost:80/api/item
Content-Type: application/json

{}

###
GET http://127.0.0.1:8000/get_matching_table
Accept: application/json

###
POST http://127.0.0.1:8000/match_with_etalon
###

POST http://localhost:8000/match_with_etalon/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="train1000.csv"

< train1000.csv











